// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "image": {
      name: "image",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/image.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/image.tsx")),
      source: "",
      meta: undefined,
    },
    "image-demo": {
      name: "image-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image"],
      files: [{
        path: "registry/default/examples/image-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/image-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "typography": {
      name: "typography",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/typography.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/typography.tsx")),
      source: "",
      meta: undefined,
    },
    "stack": {
      name: "stack",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/stack.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/stack.tsx")),
      source: "",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.tsx",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      meta: undefined,
    },
    "use-toast": {
      name: "use-toast",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-toast.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      meta: undefined,
    },
    "typography-demo": {
      name: "typography-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h1": {
      name: "typography-h1",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h1.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h1.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h2": {
      name: "typography-h2",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h2.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h2.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h3": {
      name: "typography-h3",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h3.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h3.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h4": {
      name: "typography-h4",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h4.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h4.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h5": {
      name: "typography-h5",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h5.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h5.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-p": {
      name: "typography-p",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-p.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-p.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-large-bold": {
      name: "typography-large-bold",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-large-bold.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-large-bold.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-small": {
      name: "typography-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-small.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-small.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-small-bold": {
      name: "typography-small-bold",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-small-bold.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-small-bold.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-extra-small": {
      name: "typography-extra-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-extra-small.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-extra-small.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-extra-small-bold": {
      name: "typography-extra-small-bold",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-extra-small-bold.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-extra-small-bold.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-demo": {
      name: "stack-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-align-items": {
      name: "stack-align-items",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-align-items.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-align-items.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-direction": {
      name: "stack-direction",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-direction.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-direction.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-divider": {
      name: "stack-divider",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-divider.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-divider.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-justify-content": {
      name: "stack-justify-content",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-justify-content.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-justify-content.tsx")),
      source: "",
      meta: undefined,
    },
  },
}
