// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "autocomplete": {
      name: "autocomplete",
      description: "",
      type: "registry:ui",
      registryDependencies: ["skeleton","custom/command"],
      files: [{
        path: "registry/default/akasha-ui/autocomplete.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/autocomplete.tsx")),
      source: "",
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: ["custom/typography"],
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      meta: undefined,
    },
    "circular-progress": {
      name: "circular-progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/circular-progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/circular-progress.tsx")),
      source: "",
      meta: undefined,
    },
    "copy-to-clipboard": {
      name: "copy-to-clipboard",
      description: "",
      type: "registry:ui",
      registryDependencies: ["tooltip"],
      files: [{
        path: "registry/default/akasha-ui/copy-to-clipboard.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/copy-to-clipboard.tsx")),
      source: "",
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command.tsx")),
      source: "",
      meta: undefined,
    },
    "duplex-button": {
      name: "duplex-button",
      description: "",
      type: "registry:ui",
      registryDependencies: ["custom/button"],
      files: [{
        path: "registry/default/akasha-ui/duplex-button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/duplex-button.tsx")),
      source: "",
      meta: undefined,
    },
    "error-loader": {
      name: "error-loader",
      description: "",
      type: "registry:ui",
      registryDependencies: ["custom/card","custom/image"],
      files: [{
        path: "registry/default/akasha-ui/error-loader.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/error-loader.tsx")),
      source: "",
      meta: undefined,
    },
    "form": {
      name: "form",
      description: "",
      type: "registry:ui",
      registryDependencies: ["label"],
      files: [{
        path: "registry/default/ui/form.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/form.tsx")),
      source: "",
      meta: undefined,
    },
    "icon-container": {
      name: "icon-container",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/icon-container.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/icon-container.tsx")),
      source: "",
      meta: undefined,
    },
    "image": {
      name: "image",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/image.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/image.tsx")),
      source: "",
      meta: undefined,
    },
    "infinite-scroll": {
      name: "infinite-scroll",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/infinite-scroll.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/hooks/use-scroll-restoration.ts",
        type: "registry:hook",
        target: ""
      },{
        path: "registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/infinite-scroll.tsx")),
      source: "",
      meta: undefined,
    },
    "inline-notification": {
      name: "inline-notification",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/inline-notification.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/inline-notification.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button": {
      name: "profile-avatar-button",
      description: "",
      type: "registry:ui",
      registryDependencies: ["custom/profile-avatar","custom/stack","custom/icon-container","custom/typography"],
      files: [{
        path: "registry/default/akasha-ui/profile-avatar-button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/profile-avatar-button.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar": {
      name: "profile-avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/profile-avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/profile-avatar.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner": {
      name: "sonner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sonner.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sonner.tsx")),
      source: "",
      meta: undefined,
    },
    "stack": {
      name: "stack",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/stack.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/stack.tsx")),
      source: "",
      meta: undefined,
    },
    "stacked-avatar": {
      name: "stacked-avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/stacked-avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/stacked-avatar.tsx")),
      source: "",
      meta: undefined,
    },
    "stepper": {
      name: "stepper",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/stepper.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/stepper.tsx")),
      source: "",
      meta: undefined,
    },
    "typography": {
      name: "typography",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/akasha-ui/typography.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/akasha-ui/typography.tsx")),
      source: "",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.tsx",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      meta: undefined,
    },
    "use-toast": {
      name: "use-toast",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-toast.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      meta: undefined,
    },
    "use-scroll-restoration": {
      name: "use-scroll-restoration",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-scroll-restoration.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/hooks/use-scroll-restoration.ts")),
      source: "",
      meta: undefined,
    },
    "copy-to-clipboard-demo": {
      name: "copy-to-clipboard-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["copy-to-clipboard"],
      files: [{
        path: "registry/default/examples/copy-to-clipboard-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/copy-to-clipboard-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stepper-demo": {
      name: "stepper-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stepper"],
      files: [{
        path: "registry/default/examples/stepper-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stepper-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "autocomplete-demo": {
      name: "autocomplete-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["autocomplete"],
      files: [{
        path: "registry/default/examples/autocomplete-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/autocomplete-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "autocomplete-multiple-demo": {
      name: "autocomplete-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["autocomplete"],
      files: [{
        path: "registry/default/examples/autocomplete-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/autocomplete-multiple-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-secondary.tsx")),
      source: "",
      meta: undefined,
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-destructive.tsx")),
      source: "",
      meta: undefined,
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-outline.tsx")),
      source: "",
      meta: undefined,
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-ghost.tsx")),
      source: "",
      meta: undefined,
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-link.tsx")),
      source: "",
      meta: undefined,
    },
    "button-with-icon": {
      name: "button-with-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-with-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-with-icon.tsx")),
      source: "",
      meta: undefined,
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-loading.tsx")),
      source: "",
      meta: undefined,
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-icon.tsx")),
      source: "",
      meta: undefined,
    },
    "button-as-child": {
      name: "button-as-child",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-as-child.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-as-child.tsx")),
      source: "",
      meta: undefined,
    },
    "card-demo": {
      name: "card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["card","button","switch"],
      files: [{
        path: "registry/default/examples/card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/card-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "circular-progress-demo": {
      name: "circular-progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["circular-progress"],
      files: [{
        path: "registry/default/examples/circular-progress-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/circular-progress-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "duplex-button-demo": {
      name: "duplex-button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["duplex-button"],
      files: [{
        path: "registry/default/examples/duplex-button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/duplex-button-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "error-loader-demo": {
      name: "error-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["card","image"],
      files: [{
        path: "registry/default/examples/error-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/error-loader-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "icon-container-demo": {
      name: "icon-container-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/icon-container-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/icon-container-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "icon-container-round": {
      name: "icon-container-round",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/icon-container-round.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/icon-container-round.tsx")),
      source: "",
      meta: undefined,
    },
    "icon-container-square": {
      name: "icon-container-square",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/icon-container-square.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/icon-container-square.tsx")),
      source: "",
      meta: undefined,
    },
    "icon-container-notification-dot": {
      name: "icon-container-notification-dot",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/icon-container-notification-dot.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/icon-container-notification-dot.tsx")),
      source: "",
      meta: undefined,
    },
    "image-demo": {
      name: "image-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image"],
      files: [{
        path: "registry/default/examples/image-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/image-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "infinite-scroll-demo": {
      name: "infinite-scroll-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["infinite-scroll-demo"],
      files: [{
        path: "registry/default/examples/infinite-scroll-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/infinite-scroll-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "inline-notification-demo": {
      name: "inline-notification-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["inline-notification"],
      files: [{
        path: "registry/default/examples/inline-notification-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/inline-notification-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "inline-notification-info": {
      name: "inline-notification-info",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/inline-notification-info.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/inline-notification-info.tsx")),
      source: "",
      meta: undefined,
    },
    "inline-notification-success": {
      name: "inline-notification-success",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/inline-notification-success.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/inline-notification-success.tsx")),
      source: "",
      meta: undefined,
    },
    "inline-notification-destructive": {
      name: "inline-notification-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-container"],
      files: [{
        path: "registry/default/examples/inline-notification-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/inline-notification-destructive.tsx")),
      source: "",
      meta: undefined,
    },
    "input-form": {
      name: "input-form",
      description: "",
      type: "registry:example",
      registryDependencies: ["input","button","form"],
      files: [{
        path: "registry/default/examples/input-form.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-form.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button-demo": {
      name: "profile-avatar-button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar-button"],
      files: [{
        path: "registry/default/examples/profile-avatar-button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-button-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button-large-vertical": {
      name: "profile-avatar-button-large-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar-button"],
      files: [{
        path: "registry/default/examples/profile-avatar-button-large-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-button-large-vertical.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button-large-horizontal": {
      name: "profile-avatar-button-large-horizontal",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar-button"],
      files: [{
        path: "registry/default/examples/profile-avatar-button-large-horizontal.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-button-large-horizontal.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button-medium": {
      name: "profile-avatar-button-medium",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar-button"],
      files: [{
        path: "registry/default/examples/profile-avatar-button-medium.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-button-medium.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-button-small": {
      name: "profile-avatar-button-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar-button"],
      files: [{
        path: "registry/default/examples/profile-avatar-button-small.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-button-small.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-demo": {
      name: "profile-avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar"],
      files: [{
        path: "registry/default/examples/profile-avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-nsfw": {
      name: "profile-avatar-nsfw",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar"],
      files: [{
        path: "registry/default/examples/profile-avatar-nsfw.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-nsfw.tsx")),
      source: "",
      meta: undefined,
    },
    "profile-avatar-size": {
      name: "profile-avatar-size",
      description: "",
      type: "registry:example",
      registryDependencies: ["profile-avatar"],
      files: [{
        path: "registry/default/examples/profile-avatar-size.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/profile-avatar-size.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-demo": {
      name: "stack-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-align-items": {
      name: "stack-align-items",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-align-items.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-align-items.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-direction": {
      name: "stack-direction",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-direction.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-direction.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-divider": {
      name: "stack-divider",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-divider.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-divider.tsx")),
      source: "",
      meta: undefined,
    },
    "stack-justify-content": {
      name: "stack-justify-content",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stack-justify-content.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stack-justify-content.tsx")),
      source: "",
      meta: undefined,
    },
    "stacked-avatar-demo": {
      name: "stacked-avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stack"],
      files: [{
        path: "registry/default/examples/stacked-avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stacked-avatar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-demo": {
      name: "sonner-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-info": {
      name: "sonner-info",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-info.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-info.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-success": {
      name: "sonner-success",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-success.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-success.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-warning": {
      name: "sonner-warning",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-warning.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-warning.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-error": {
      name: "sonner-error",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-error.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-error.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-demo": {
      name: "typography-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h1": {
      name: "typography-h1",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h1.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h1.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h2": {
      name: "typography-h2",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h2.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h2.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h3": {
      name: "typography-h3",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h3.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h3.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h4": {
      name: "typography-h4",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h4.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h4.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h5": {
      name: "typography-h5",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h5.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h5.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-h6": {
      name: "typography-h6",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-h6.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-h6.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-p": {
      name: "typography-p",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-p.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-p.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-small": {
      name: "typography-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-small.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-small.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-small-bold": {
      name: "typography-small-bold",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-small-bold.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-small-bold.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-extra-small": {
      name: "typography-extra-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-extra-small.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-extra-small.tsx")),
      source: "",
      meta: undefined,
    },
    "typography-extra-small-bold": {
      name: "typography-extra-small-bold",
      description: "",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: [{
        path: "registry/default/examples/typography-extra-small-bold.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/typography-extra-small-bold.tsx")),
      source: "",
      meta: undefined,
    },
  },
}
